### ISSUE TITLE
static access

### ISSUE THREAD

**Issue by omry** [andrasmaroy/pconf#2]
This is not an issue, but I am wondering about the design decision to use classmethods (aka static) to create the configuration.
this seems to limit usefulness for cases were you want more than one configuration (such as - but not only - unit tests).

**Comment by omry** [comment]
This seems to also limiting the functionality:
for example, I would like to be able to load several configuration files:

    Pconf.file('common.yaml', encoding='yaml')
    Pconf.file('subtask1-specific.yaml', encoding='yaml')
    Pconf.file('subtask1-specific.yaml', encoding='yaml')

And have all sources flattened by load order, but this does not seem possible because file() only allows one file to be loaded at a time.

**Comment by andrasmaroy** [comment]
The idea behind the front being static is that most of the time in an application you won't have multiple configurations in one run and this design makes it easier to use in this case.

To allow use in cases with more than one configuration I might add a `reset()` or `clear()` function that would clear the current configuration.

As for flattening file names I'd just do it like this:
```
files = ['common.yaml', 'subtask1-specific.yaml', 'subtask2-specific.yaml']`
for file in files:
  Pconf.file(file, encoding='yaml')
```
This way you have flattened file names. It is not flattened in one call, but you still have the file names like that and it is consistent with the current design.

**Comment by omry** [comment]
for some reason I thought it didn't work, maybe I had the wrong file name (or bad path).
