### ISSUE TITLE
Pconf.argv: Accept parsed argparse args

### ISSUE THREAD

**Issue by fleimgruber** [andrasmaroy/pconf#28]
This is a feature request, I will try to follow the predefined structure where it is reasonable.

## Expected Behavior

Given an existing code base that uses stdlib `argparse` module and provides parsed args via its `parsed_args = argparse.ArgumentParser(...).parse_args()`, the user should be able to use e.g. `Pconf.argv(argparse=parsed_args)`.

## Actual Behavior

The API of `Pconf.argv` does not support this.

**Comment by andrasmaroy** [comment]
You can do this, not with the `argv` module, but with the `overrides` module:
```python
parsed_args = argparse.ArgumentParser(...).parse_args()
Pconf.overrides(vars(parsed_args))
```
Place this wherever it fits your configuration hierarchy and it will insert all your arguments parsed by `argparse` in that position.

**Comment by fleimgruber** [comment]
Oh, nice! Thanks, I will try this tomorrow. WDYT, might be good to mention this in the docs?

**Comment by andrasmaroy** [comment]
To be honest I'd rather people just migrate from argparse to pconf, the whole point here is to be able to manage all of your configuration in one place/structure.

A case where migrating wouldn't be an option is if people are using more options provided by argparse that are not exposed here. To solve that I'm happy to add more options here or the ability to pass argparse options through, as I think that still is a more consistent structure than having to maintain configuration in both argparse and pconf.

**Comment by fleimgruber** [comment]
> To be honest I'd rather people just migrate from argparse to pconf, the whole point here is to be able to manage all of your configuration in one place/structure.

I see the point and I would agree if people would use argparse only for configuration values. But it is also used in some cases to implement command structures (even subcommands) or mode-like behaviour, e.g.

```
python ops.py --add 1 2 3
```

Where I would not consider "add" as a config variable.

I would use the proposed feature in a code base where _some_ of the args are actually config parameters. In those cases it is arguably even more consistent to have config variables separated from non-config variables. But come to think of it your suggested use of `overrides` is even better as one can explicitly choose which args are actually config vars and only use those.

> A case where migrating wouldn't be an option is if people are using more options provided by argparse that are not exposed here. To solve that I'm happy to add more options here or the ability to pass argparse options through, as I think that still is a more consistent structure than having to maintain configuration in both argparse and pconf.

I don't think you would want to reimplement (even a subset of) argparse here in pconf, but just my 2ct.

Thanks for the package in any case!

**Comment by andrasmaroy** [comment]
That is fair point I did not think about, I agree. I'll add the above snippet to the readme with some context about this topic.

Thank you for bringing this up!
