### ISSUE TITLE
Calling Pconf.get() multiple times causes configuration flips due to order failure

### ISSUE THREAD

**Issue by ronsinai** [andrasmaroy/pconf#31]
Calling Pconf.get() multiple times fails to return the same configuration (order of storeMethods flips / reverses).

Scenario (`COMPUTERNAME=aws-ron`)
```
Pconf.env()
Pconf.defaults({'COMPUTERNAME': 'localhost'})

print(Pconf.get()) # ==> {'COMPUTERNAME': 'aws-ron', ...}
print(Pconf.get()) # ==> {'COMPUTERNAME': 'localhost', ...}
print(Pconf.get()) # ==> {'COMPUTERNAME': 'aws-ron', ...}
print(Pconf.get()) # ==> {'COMPUTERNAME': 'localhost', ...}
...
```

Quick fix: do not reverse the hierarchy in-place, but use Python's array bracket operator to reverse it:
`hierarchy = cls.__hierarchy[::-1]`

https://github.com/ronsinai/pconf/blob/master/pconf/pconf.py#L36
https://github.com/ronsinai/pconf/blob/master/pconf/pconf.py#L37

**Comment by andrasmaroy** [comment]
Thanks for reporting and fixing, new version 1.7.2 with the fix is released.

**Comment by ronsinai** [comment]
@andrasmaroy np, thanks for the quick response!
